mozilla/task-boot

- requirements.txt
- taskboot/build.py
- taskboot/docker.py
- tests/conftest.py
- tests/test_docker.py
Due to https://github.com/genuinetools/img/issues/206, taskboot needs to patch target's Dockerfile when using `build-compose` in order to use local images first, before trying the remote repo.
Just miss unit tests...
> Local images support

- taskboot/build.py
- taskboot/cli.py
- taskboot/docker.py
Build args are global for all the services, users will need to handle
namespacing themselves.
> Add support for build args in build-compose subcommand

- taskboot/cli.py
- taskboot/push.py
We have the use in the Mozilla bugbug project where we want to build a Docker
image but don't push it in a first time.
> Add support for an exclude filter in push-artifact subcommand

- taskboot/cli.py
When testing locally and without this patch, I got the following traceback:
```
Traceback (most recent call last):
File ".../bin/taskboot", line 11, in <module>
load_entry_point('task-boot', 'console_scripts', 'taskboot')()
File ".../task-boot/taskboot/cli.py", line 146, in main
args.func(target, args)
File ".../task-boot/taskboot/build.py", line 122, in build_compose
retries=args.build_retries,
File ".../task-boot/taskboot/utils.py", line 20, in retry
return operation()
File ".../task-boot/taskboot/build.py", line 120, in <lambda>
lambda: docker.build(context, dockerfile, tag, args.build_arg),
File ".../task-boot/taskboot/docker.py", line 99, in build
for single_build_arg in build_args:
TypeError: 'NoneType' object is not iterable
```
> Fix default Docker build args

- .taskcluster.yml
- taskboot/build.py
- taskboot/cli.py
- taskboot/docker.py
The use-case is the following:
- The docker-compose contains images untagged or tagged with `latest`. We want
those images and push them.
- We also to pushed tagged images with the git tag. The git tag is known only
at runtime.
Add the `--additional-tags` that will takes the image name from docker-compose
and add or replace the tag by the given CLI argument and add this as a new
tag. `push-artifacts` should handle those additional tags without issues.
> Add support for additional tags when building

- taskboot/cli.py
- taskboot/push.py
The previous version only allowed to deploy one dyno type at a time. For
projects with multiple dyno type, it is problematic.
This change is backward incompatible and replace the old CLI api with a new
one allowing to pass multiple dyno-type:artifact mapping. For example:
```
taskboot deploy-heroku --heroku-app bugbug \
"web:public/bugbug/bugbug-http-service.tar" \
"worker:public/bugbug/bugbug-http-service-bg-worker.tar"
```
All the artifact are retrieves pushed and then only one call is made to Heroku
API to deploy them atomically.
> Update the heroku command to being able to allow atomic deloy

- taskboot/push.py
The payload structure was modified by #46. Also adds some logs so we can
better understand what is happening
> Fix the Heroku deploy payload

- .isort.cfg
- requirements.txt
- taskboot/build.py
- taskboot/config.py
This should generate the correct URL regardless of rootUrl.
> Bug 1578593 - use taskcluster-urls to generate UI link

- taskboot/config.py
Reverts mozilla/task-boot#77
We were already using it in get_root_url.
> Revert "Use Taskcluster root url environment variable"

- .taskcluster.yml
(context: [bug 1574665](https://bugzilla.mozilla.org/show_bug.cgi?id=1574665))
We'll still need to make the secrets in the new deployment in order for this to work but that is blocked on [bug 1593896](https://bugzilla.mozilla.org/show_bug.cgi?id=1593896) at the moment. I wanted to get this up for review to see if it made sense to you all. @La0 and @marco-c in particular.
*Note: this will fail until the github app that provides tc is switched which we would do right before we land this.*
> Update .taskcluster.yml for community cluster

- taskboot/docker.py
To avoid [this intermittent issue](https://community-tc.services.mozilla.com/tasks/GfbFp-cxTPW4XF376MSmNw/runs/1/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FGfbFp-cxTPW4XF376MSmNw%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log) from the remote docker daemon
> Retry reading daemon output on ReadError

- taskboot/artifacts.py
- taskboot/cli.py
> Remove an useless part from a download-artifact's option

- Dockerfile
- taskboot/cargo.py
- taskboot/cli.py
- taskboot/config.py
> Add a command to publish a crate on crates.io

- taskboot/cli.py
- taskboot/git.py
This PR fixes #159 
I tested it locally and it works.
> Add a command to push on a git repository

- taskboot/config.py
- taskboot/git.py
- taskboot/github.py
The `has_github_auth` has been renamed to `has_git_auth`. We need to change the token name in the `yml` file also.
> Rename Git auth function to explain it is not strictly related to GitHub

- taskboot/cargo.py
Pusblish a crate on `crates.io` without building it, this check is now demanded to the maintainer of a project.
> Publish a crate without building it

- .taskcluster.yml
Use `python:3.7` Docker image instead of `python:3.7-alpine`
Thanks in advance for your review!
> CI: Fix docker build

- taskboot/cargo.py
- taskboot/cli.py
This PR checks whether a crate has already been published on `crates.io` before running the `cargo publish` command. 
> Check whether a crate has already been published

- taskboot/target.py
Sometimes `GIT_REVISION` is not part of the default tree fetched by clone. This happens when revision is from a forked repo with an open PR.
Originally logged the issue as https://github.com/MozillaSecurity/orion/issues/128
> Fetch revision if not present from clone.

- Dockerfile
- taskboot/build.py
- taskboot/cli.py
- taskboot/docker.py
- taskboot/push.py
This is a drop-in replacement for docker, although it still requires `--privileged` like `img`.
`img` is not maintained (see https://github.com/genuinetools/img/issues/348)
> Add support for podman.

- .taskcluster.yml
PR #377 was created when we migrated from Docker Worker to Generic Worker, removing an unneeded scope. However, since we reverted back to Docker Worker, that scope is needed again. This reinstates the scope that was previously removed.
> Revert #377

- .taskcluster.yml
- Dockerfile
- Makefile
- README.md
- taskboot/build.py
- taskboot/cli.py
- taskboot/docker.py
- tests/conftest.py
- tests/test_docker.py
Regarding https://github.com/mozilla/code-review/pull/1895#issuecomment-1727493931.
> chore!: use `podman` as default build tool and remove `img`

- .taskcluster.yml
Taskboot v0.4.0 was accidentally built using `tests/dockerfile.empty`.
> fix(release): separate out a release docker build from a test docker build

- taskboot/build.py
- taskboot/cli.py
- taskboot/docker.py
Ran into that issue [here](https://community-tc.services.mozilla.com/tasks/bRJoqd5dTvqCfakcAM3jig/runs/0/logs/public/logs/live.log#L163). We'll need to remove `--cache` usages of taskboot too now.
> fix: remove unused cache option

- .taskcluster.yml
I noticed that `mozilla/task-boot` is not filtering pull request events, which results in builds for such events like:
- `pull_request.edited`
- `pull_request.ready_for_review`
- `pull_request.converted_to_draft`
- `pull_request.review_requested`
- `pull_request.auto_merge_enabled`
We only want `opened`, `reopened` and `synchronize` events
Here's what it looks like in debug tool: [existing .taskcluster.yml](https://community-tc.services.mozilla.com/tcyaml-debug?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmozilla%2Ftask-boot%2Fmaster%2F.taskcluster.yml#findings)
and here's how for [updated .taskcluster.yml](https://community-tc.services.mozilla.com/tcyaml-debug?url=https%3A%2F%2Fraw.githubusercontent.com%2Flotas%2Ftask-boot%2Fchore%2Ftc-yml%2F.taskcluster.yml#findings)
> Filter out github-pull-request events don't run builds on irrelevant ones

- taskboot/git.py
- taskboot/target.py
Fixes #418
I've tested `Target` locally using:
- `--git-repository https://github.com/MozillaSecurity/orion --git-revision master`
- `--git-repository https://github.com/MozillaSecurity/orion --git-revision edb3e91c4deb1d7920fc7cd4171b16e6b9e43fe4`
> Retry git network operations

- .taskcluster.yml
- requirements.txt
We (taskcluster team) will soon be removing support for Ubuntu 22.04 in Community deployment of taskcluster.
> Migrate from Ubuntu 22.04 to Ubuntu 24.04 in CI

- taskboot/cli.py
- taskboot/github.py
> Add a command to trigger a repository dispatch event
